auth:
  - user: nas
    group: nas
    uid: 1000
    gid: 1000
    password_file: /run/secrets/samba_password

global:
  - "server string = NAS_Jetson_Nano"
  - "server role = standalone server"
  - "log level = 0"
  - "map to guest = bad user"

share:
  - name: public
    comment: NAS_Jetson_Nano Public Share
    path: /mnt/public
    browsable: yes
    readonly: no
    guestok: yes
    veto: no

  - name: nextcloud
    comment: Nextcloud Files
    path: /mnt/nc-data
    browsable: yes
    readonly: yes
    guestok: no
    users:
      - nas

  - name: immich
    comment: Immich Photos (read-only)
    path: /mnt/immich-data
    browsable: yes
    readonly: yes
    guestok: no
    users:
      - nas
